mlibrary/blueprints/auth.py
# -*- coding: utf-8 -*-
"""
    :author: Jinfen Li
    :url: https: // github.com / LiJinfen
"""
from flask import render_template, flash, redirect, url_for, Blueprint, request
from flask_login import login_user, logout_user, login_required, current_user

from mlibrary.extensions import db
from mlibrary.models import User

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():

    if current_user.is_authenticated:
        return redirect(url_for('song.home'))

    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        remember_me = request.form.get('remember', False)

        if remember_me:
            remember_me = True

        user1 = User.query.filter_by(email=email).first()
        user2 = User.query.filter_by(nickname=email).first()
        user = user1 if user1 else user2


        if user is not None:
            if user.password_hash is None:
                flash('Please use the third party service to log in.')
                return redirect(url_for('.login'))

            if user.verify_password(password):
                login_user(user, remember_me)
                return redirect(url_for('song.home'))
        flash('Either the email/nickname or password was incorrect.')
        return redirect(url_for('.login'))

    return render_template('auth/login.html')


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('song.index'))


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('song.index'))

    if request.method == 'POST':
        email = request.form['email'].lower()
        nickname = request.form['nickname']


        user = User.query.filter_by(email=email).first()
        if user is not None:
            flash('The email is already registered, please log in.')
            return redirect(url_for('.login'))
        user = User.query.filter_by(nickname=nickname).first()
        if user is not None:
            flash('The nickname is already registered, please log in.')
            return redirect(url_for('.login'))

        password = request.form['password']

        user = User(nickname=nickname, email=email)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        login_user(user, remember=True)
        return redirect(url_for('song.index'))

    return render_template('auth/register.html')


@auth_bp.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    if current_user.is_authenticated:
        return redirect(url_for('song.index'))

    if request.method == 'POST':
        nickname = request.form['nickname']


        user = User.query.filter_by(nickname=nickname).first()
        if user is None:
            flash('The user is not registered!')
            return redirect(url_for('.reset_password'))


        password = request.form['password']
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.login'))

    return render_template('auth/reset_password.html')

mlibrary/blueprints/song.py
"""
    :author: Jinfen Li
    :url: https://github.com/LiJinfen
"""

from flask import render_template, redirect, url_for, request, Blueprint, jsonify
from flask_login import current_user, login_required
from flask_paginate import Pagination, get_page_parameter
from mlibrary.extensions import db
from mlibrary.models import Song




song_bp = Blueprint('song', __name__)




@song_bp.route('/')
def index():

    if current_user.is_authenticated:

        return redirect(url_for('.home'))

    else:
        return render_template('auth/login.html')


@song_bp.route('/home')
@song_bp.route('/home/page1/<int:page1>')
@song_bp.route('/home/page2/<int:page2>')
def home(page1=1,page2=1):
    """
    the home page of administrator and common users
    """
    if current_user.is_authenticated:


        if current_user.is_admin:

            q1 = db.session.query(Song.name, Song.artist, db.func.count(Song.user_id)).group_by(Song.name, Song.artist).order_by(
                    Song.name.asc()
                ).paginate(page1, per_page=10)
            q2 = db.session.query(Song.artist, db.func.count(db.distinct(Song.user_id))).group_by(Song.artist, Song.user_id).order_by(
                    Song.artist.asc()
                ).paginate(page2, per_page=10)

            table1 = [[q[0], q[1],q[2]] for q in q1.items]
            table2 = [[q[0], q[1]] for q in list(set(q2.items))]

            return render_template('song/admin_home.html', table1=table1, table2=table2,q1=q1,q2=q2)
        else:

            try:
                song_list = Song.query.filter_by(user_id=current_user.id).order_by(
                    Song.createTime.desc()
                ).paginate(page1, per_page=10)
            except db.OperationalError:
                db.flash("No songs in the library.")
                song_list = None
            songs = song_list.items
            allsongs = [[song.name, song.artist, song.createTime.strftime('%Y-%m-%d')] for song in songs]
            return render_template(
                'song/user_home.html',
                song_list=song_list, songs=allsongs
            )

    else:
        return render_template('auth/login.html')


@song_bp.route('/createsong', methods=['POST'])
def createsong():
    """
    the route for a common user to add a song to the library
    """

    name = request.form['name']
    artist = request.form['artist']
    song = Song.query.filter_by(user_id=current_user.id).all()

    for s in song:
        if s.name == name and s.artist == artist:
            return jsonify({"message": 'The song already exists, please re-enter.',
                            "result": 0,
                            "error": ''
                            })


    userHasSong = Song(user_id=current_user.id, name=name, artist=artist)

    db.session.add(userHasSong)
    db.session.commit()

    data={'name':userHasSong.name,'artist':userHasSong.artist,'time':userHasSong.createTime.strftime('%Y-%m-%d'), 'id':userHasSong.id,
          'deleteurl':url_for('song.deleteroom', song_id=userHasSong.id)}


    return jsonify({"message": 'successfully added to your library!',
                    "result": 1,
                    "error": '',
                    "data":data
                    })


@song_bp.route('/song/delete/<song_id>', methods=['DELETE'])
def deleteroom(song_id):
    """
        the route for a common user to delete a song in a library
    """
    Song.query.filter_by(id=song_id).delete()
    db.session.commit()
    return '', 204

mlibrary/templates/song/admin_home.html
{% extends 'base.html' %}
{% block title %}Music Library{% endblock %}


{% block nav %}

    <div class="ui top fixed borderless menu">
        <a class="item" id="toggle-sidebar">
                <i class="sidebar icon"></i>
            </a>
        <a class="item catchat" href="{{ url_for('song.index') }}">
            <img src="{{ url_for('static', filename='logo.png') }}">
            <span>Music Library</span>
        </a>


    </div>
{% endblock %}




{% block sidebar %}
<div class="ui labeled icon left vertical inverted demo menu sidebar">
    <a class="item" href="{{ url_for('song.index') }}">
        <i class="home secret icon"></i>
        Rooms
    </a>

    {% if current_user.is_authenticated %}
        <a class="item" href="{{ url_for('auth.logout') }}">
            <i class="power off icon"></i>
            Sign out</a>
    {% endif %}

</div>
{% endblock %}



{% block content %}

    <div class="pusher">
        <div class="chat-box">

                {% include 'song/library.html' %}




        </div>

    </div>
{% endblock %}


{% block scripts %}
    {{ super() }}
    <script type="text/javascript">

    </script>
{% endblock %}

mlibrary/templates/song/library.html
     {% if current_user.is_admin %}
<div class="pusher">
        <div class="chat-box">
    <div class="container my-4">
    {% if q1.has_prev %}
<page>
    <a href="{{ url_for('song.home', page1=q1.prev_num) }}">Previous</a>
</page>
{% endif %}

<!-- all page numbers -->
{% for page_num in q1.iter_pages() %}
    {% if page_num %}
        {% if page_num != q1.page %}
            <page>
                <a href="{{ url_for('song.home', page1=page_num) }}">{{ page_num }}</a>
            </page>
        {% else %}
            <page >
                <a href="#">{{ page_num }}</a>
            </page>
        {% endif %}
   {% else %}
       <page>
           <span class="ellipsis" style="white-space; nowrap; overflow: hidden; text-overflow: ellipsis">…</span>
       </page>
   {% endif %}
{% endfor %}

<!-- next page -->
{% if q1.has_next %}
<page>
    <a href="{{ url_for('song.home', page1=q1.next_num) }}">Next</a></page>
{% endif %}
        <table class="table table-striped table-bordered grid sortable" border="1" id="table1">
                <caption class="text-center" style="border: inherit; background-color: black;caption-side: top; color:white;">Library 1</caption>

            <thead class="thead-dark" style="background-color: #23272b">
                <tr>
                    <th style="color:white">Song Title</th>
                    <th style="color:white" >Artist</th>
                    <th style="color:white" >User Count</th>

                </tr>
            </thead>
            <tbody>
                {% for t in table1 %}
                <tr>
                    <td >

                        {{ t[0] }}</td>
                    <td >{{ t[1] }}</td>
                    <td >{{ t[2] }}</td>


                {% else %}
                <td colspan="9" align="center" id="createnosong">No data so far</td>

                {% endfor %}
            </tr>
            </tbody>
        </table>




    </div>
        </div>
</div>



  <div class="pusher" style="padding: 60px;">
        <div class="chat-box">
    <div class="container my-4">
    {% if q2.has_prev %}
<page>
    <a href="{{ url_for('song.home', page2=q2.prev_num) }}">Previous</a>
</page>
{% endif %}

<!-- all page numbers -->
{% for page_num in q2.iter_pages() %}
    {% if page_num %}
        {% if page_num != q2.page %}
            <page>
                <a href="{{ url_for('song.home', page2=page_num) }}">{{ page_num }}</a>
            </page>
        {% else %}
            <page >
                <a href="#">{{ page_num }}</a>
            </page>
        {% endif %}
   {% else %}
       <page>
           <span class="ellipsis" style="white-space; nowrap; overflow: hidden; text-overflow: ellipsis">…</span>
       </page>
   {% endif %}
{% endfor %}

<!-- next page -->
{% if q2.has_next %}
<page>
    <a href="{{ url_for('song.home', page2=q2.next_num) }}">Next</a></page>
{% endif %}
      <table class="table table-striped table-bordered grid sortable" border="1" id="table2">
                <caption class="text-center" style="border: inherit; background-color: black;caption-side: top; color:white;">Library 2</caption>

            <thead class="thead-dark" style="background-color: #23272b">
                <tr>

                    <th style="color:white" >Artist</th>
                    <th style="color:white" >User Count</th>

                </tr>
            </thead>
            <tbody>
                {% for t in table2 %}
                <tr>
                    <td >

                        {{ t[0] }}</td>
                    <td >{{ t[1] }}</td>



                {% else %}
                <td colspan="9" align="center" id="createnosong">No data so far</td>

                {% endfor %}
            </tr>
            </tbody>
    </table>



    </div>
        </div>
</div>




     {% else %}
    <div class="pusher">
        <div class="chat-box">
    <div class="container my-4">
    <!-- previous page -->
{% if song_list.has_prev %}
<page>
    <a href="{{ url_for('song.home', page1=song_list.prev_num) }}">Previous</a>
</page>
{% endif %}

<!-- all page numbers -->
{% for page_num in song_list.iter_pages() %}
    {% if page_num %}
        {% if page_num != song_list.page %}
            <page>
                <a href="{{ url_for('song.home', page1=page_num) }}">{{ page_num }}</a>
            </page>
        {% else %}
            <page >
                <a href="#">{{ page_num }}</a>
            </page>
        {% endif %}
   {% else %}
       <page>
           <span class="ellipsis" style="white-space; nowrap; overflow: hidden; text-overflow: ellipsis">…</span>
       </page>
   {% endif %}
{% endfor %}

<!-- next page -->
{% if song_list.has_next %}
<page>
    <a href="{{ url_for('song.home', page1=song_list.next_num) }}">Next</a></page>
{% endif %}

<table class="table table-striped table-bordered grid" border="1" id="userlibrary">
                <caption class="text-center" style="border: inherit; background-color: black;caption-side: top; color:white;">Your Music Library</caption>
            <thead class="thead-dark" style="background-color: #23272b">
                <tr>

                    <th style="color:white">Name</th>
                    <th style="color:white">Artist</th>
                    <th style="color:white">Create Time</th>
                    <th style="color:white">Delete</th>

                </tr>
            </thead>
            <tbody>

                {% for song in songs %}
                <tr>

                    <td >{{ song[0] }}</td>
                    <td>{{ song[1] }}</td>
                    <td>{{ song[2] }}</td>

                    <td><div class="item delete-song-button"
                         data-href="{{ url_for('song.deleteroom', song_id=song[3]) }}">
                        <i class="delete icon"></i>
            </div></td>
                    {% else %}
            <td colspan="7" align="center" id="createnosong">Add your first song!</td>
                {% endfor %}
            </tbody>
        </table>
</div>
</div>
</div>

{% endif %}

mlibrary/templates/song/user_home.html
{% extends 'base.html' %}
{% block title %}Music Library{% endblock %}


{#{% block nav %}#}
{#    <div class="ui top fixed borderless menu">#}
{#        <a class="item" id="toggle-sidebar">#}
{#                <i class="sidebar icon"></i>#}
{#            </a>#}
{#        <a class="item catchat" href="{{ url_for('song.index') }}">#}
{#            <img src="{{ url_for('static', filename='logo.png') }}">#}
{#            <span>Music Library</span>#}
{#        </a>#}
{##}
{#        <div class="right menu hide-on-mobile">#}
{#            {% if current_user.is_authenticated %}#}
{#                <div class="item">#}
{#                    <button class="ui button orange basic" id="show-snippet-modal">add a song</button>#}
{#                </div>#}
{#            {% else %}#}
{#                <div class="item">#}
{#                    <a class="ui primary button" href="{{ url_for('auth.login') }}">#}
{#                        Sign in</a>#}
{#                </div>#}
{#            {% endif %}#}
{##}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}



{% block createsongModal %}

<div class="ui modal snippet small center" tabindex="-4"  id="createsongmodal">

        <div class="content">
    <div class="modal-header">Add a Song</div>
    <div class="content" align="center">
    <form class="create ui form" method="post" >

                <div class="field eight wide">
                    <label><span style="color:red;">* </span>name of the song</label>
                    <input name="name" placeholder="name" type="text" id="name" required="required">
                </div>

                <div class="field eight wide">
                    <label><span style="color:red;">* </span>artist of the song</label>
                    <input name="artist" placeholder="artist" type="text" id="artist" required="required">
                </div>


            </form>
</div>
    <div class="actions">
        <button class="ui button cancel">Cancel</button>
        <button class="ui button blue approve" id="createsong">Add</button>
    </div>

        </div>

</div>


{% endblock %}

{% block sidebar %}
<div class="ui labeled icon left vertical inverted demo menu sidebar">
    <a class="item" href="{{ url_for('song.index') }}">
        <i class="home secret icon"></i>
        Library
    </a>

    {% if current_user.is_authenticated %}
        <a class="add icon item" id="show-snippet-modal"><i class="add icon"></i>Add a Song</a>
        <a class="item" href="{{ url_for('auth.logout') }}">
            <i class="power off icon"></i>
            Sign out</a>
    {% endif %}

</div>
{% endblock %}


{% block content %}

    <div class="pusher">
        <div class="chat-box">

                {% include 'song/library.html' %}




        </div>

    </div>
{% endblock %}


{% block scripts %}
    {{ super() }}
    <script type="text/javascript">

    </script>
{% endblock %}